[package]
name = "parseval"
version = "0.1.0"
authors = ["Michael Angerman <stormasm@gmail.com>"]
edition = "2018"

[dependencies]
nu-engine = {git = "https://github.com/nushell/nushell.git", branch = "main", default-features = false}
